apiVersion: v1
kind: Service
metadata:
  name: muvico-staging-svc
spec:
  selector:
    app: muvico-staging
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80  
  type: ClusterIP
